# Generated by Django 3.2.6 on 2021-08-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schema_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_schema', models.CharField(max_length=200)),
                ('Job', models.BooleanField()),
                ('Email', models.BooleanField()),
                ('Domain', models.BooleanField()),
                ('Phone', models.BooleanField()),
                ('Company', models.BooleanField()),
                ('Text', models.BooleanField()),
                ('Integer', models.BooleanField()),
                ('Address', models.BooleanField()),
                ('Date', models.BooleanField()),
                ('schema_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv_app.schema_list')),
            ],
        ),
    ]
