# Generated by Django 3.2.6 on 2021-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='Address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Integer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='Text',
            field=models.BooleanField(default=False),
        ),
    ]
