# Generated by Django 3.2.6 on 2021-08-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0002_auto_20210829_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='Phone',
        ),
        migrations.AddField(
            model_name='schema',
            name='rows',
            field=models.IntegerField(default=1),
        ),
    ]
