# Generated by Django 3.2.6 on 2021-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0003_auto_20210829_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='last_mod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
