# Generated by Django 3.2.6 on 2021-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0004_schema_last_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_cep',
            field=models.CharField(choices=[('Comma(,)', ','), ('Semicolon(;)', ';')], default='Comma(,)', max_length=20),
        ),
    ]
