# Generated by Django 3.2.6 on 2021-08-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0005_schema_column_cep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schema_list',
            new_name='SchemaList',
        ),
    ]
