# Generated by Django 3.2.6 on 2021-08-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0006_rename_schema_list_schemalist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='schema_list',
            new_name='SchemaList',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Integer',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='Text',
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_field', models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], max_length=20)),
                ('name_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv_app.schema')),
            ],
        ),
    ]
