# Generated by Django 3.2.6 on 2021-08-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0007_auto_20210830_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemacolumn',
            old_name='name_schema',
            new_name='Schema',
        ),
    ]
