# Generated by Django 3.2.6 on 2021-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0008_rename_name_schema_schemacolumn_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='column_field2',
            field=models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
