# Generated by Django 3.2.6 on 2021-08-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0009_schemacolumn_column_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='SchemaList',
        ),
        migrations.DeleteModel(
            name='SchemaList',
        ),
    ]
