# Generated by Django 3.2.6 on 2021-08-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0010_auto_20210830_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='column_field2',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='order_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
