# Generated by Django 3.2.6 on 2021-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_app', '0011_auto_20210830_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='order_by',
            field=models.IntegerField(choices=[('1', 1), ('2', 2)]),
        ),
    ]
