# Generated by Django 3.2.6 on 2021-09-04 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210831_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_field1',
            field=models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='column_field2',
            field=models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='column_field3',
            field=models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SchemaColumn',
        ),
    ]
