# Generated by Django 3.2.6 on 2021-09-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_schema_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='column_field2',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='column_field3',
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_column', models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], max_length=60)),
                ('min_choise', models.IntegerField()),
                ('max_choise', models.IntegerField()),
                ('name_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schema')),
            ],
        ),
    ]
