# Generated by Django 3.2.6 on 2021-09-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210904_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='max_choise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='min_choise',
            field=models.IntegerField(default=0),
        ),
    ]
