# Generated by Django 3.2.6 on 2021-09-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210904_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='type_column',
            field=models.CharField(choices=[('Job', 'Job'), ('Email', 'Email')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='name_column',
            field=models.CharField(max_length=60),
        ),
    ]
