# Generated by Django 3.2.6 on 2021-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_schema_name_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='rows',
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', '"'), ("'", "'")], default='"', max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='type_column',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=60),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_field1',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=20),
        ),
    ]
