# Generated by Django 3.2.6 on 2021-09-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210905_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name_schema',
            field=models.CharField(max_length=200),
        ),
    ]
