# Generated by Django 3.2.6 on 2021-09-05 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_schema_name_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name_schema',
            field=models.CharField(default=uuid.uuid1, max_length=200),
        ),
    ]
