# Generated by Django 3.2.6 on 2021-09-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_schema_name_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='string_character',
        ),
    ]
