# Generated by Django 3.2.6 on 2021-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_schema_string_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', '"'), ("'", "'")], default='"', max_length=20),
        ),
    ]
