# Generated by Django 3.2.6 on 2021-09-05 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_schema_string_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='max_choise',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='min_choise',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name_schema',
            field=models.CharField(default=uuid.uuid1, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('Not send', 'Not send'), ('Processed', 'Processed'), ('Ready', 'Ready')], max_length=20)),
                ('download_link', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
