# Generated by Django 3.2.6 on 2021-09-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210905_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='id_schema',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.schema'),
            preserve_default=False,
        ),
    ]
