# Generated by Django 3.2.6 on 2021-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sets_id_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
