# Generated by Django 3.2.6 on 2021-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_id_schema_sets_name_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='rows',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sets',
            name='status',
            field=models.CharField(choices=[('error', 'error'), ('Processed', 'Processed'), ('Ready', 'Ready')], max_length=20),
        ),
    ]
