# Generated by Django 3.2.6 on 2021-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210905_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_cep',
            field=models.CharField(choices=[(',', ','), (';', ';')], default='Comma(,)', max_length=20),
        ),
    ]
